In [33]:
import pandas as pd
import numpy as np

In [34]:
chunks = pd.read_csv("taxi_route.csv", chunksize=1000000)

In [35]:
chunk_list = []  # append each chunk df here 

# Each chunk is in df format
for chunk in chunks:  
    # Once the data filtering is done, append the chunk to list
    chunk_list.append(chunk)
    
routes = pd.concat(chunk_list, axis= 0)

In [36]:
routes

,TRIP_ID,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
0,1372636858620000589,C,NaN,NaN,20000589,1372636858,A,False,"[[-8.618643,41.141412],[-8.618499,41.141376],[..."
1,1372637303620000596,B,NaN,7.0,20000596,1372637303,A,False,"[[-8.639847,41.159826],[-8.640351,41.159871],[..."
2,1372636951620000320,C,NaN,NaN,20000320,1372636951,A,False,"[[-8.612964,41.140359],[-8.613378,41.14035],[-..."
3,1372636854620000520,C,NaN,NaN,20000520,1372636854,A,False,"[[-8.574678,41.151951],[-8.574705,41.151942],[..."
4,1372637091620000337,C,NaN,NaN,20000337,1372637091,A,False,"[[-8.645994,41.18049],[-8.645949,41.180517],[-..."
5,1372636965620000231,C,NaN,NaN,20000231,1372636965,A,False,"[[-8.615502,41.140674],[-8.614854,41.140926],[..."
6,1372637210620000456,C,NaN,NaN,20000456,1372637210,A,False,"[[-8.57952,41.145948],[-8.580942,41.145039],[-..."
7,1372637299620000011,C,NaN,NaN,20000011,1372637299,A,False,"[[-8.617563,41.146182],[-8.617527,41.145849],[..."
8,1372637274620000403,C,NaN,NaN,20000403,1372637274,A,False,"[[-8.611794,41.140557],[-8.611785,41.140575],[..."
9,1372637905620000320,C,NaN,NaN,20000320,1372637905,A,False,"[[-8.615907,41.140557],[-8.614449,41.141088],[..."
10,1372636875620000233,C,NaN,NaN,20000233,1372636875,A,False,"[[-8.619894,41.148009],[-8.620164,41.14773],[-..."
11,1372637984620000520,C,NaN,NaN,20000520,1372637984,A,False,"[[-8.56242,41.168403],[-8.562429,41.168358],[-..."
12,1372637343620000571,A,31508.0,NaN,20000571,1372637343,A,False,"[[-8.618868,41.155101],[-8.6175,41.154912],[-8..."
13,1372638595620000233,C,NaN,NaN,20000233,1372638595,A,False,"[[-8.608716,41.153499],[-8.607627,41.153481],[..."
14,1372638151620000231,C,NaN,NaN,20000231,1372638151,A,False,"[[-8.612208,41.14053],[-8.612235,41.140521],[-..."
15,1372637610620000497,B,NaN,13.0,20000497,1372637610,A,False,"[[-8.585145,41.164857],[-8.584146,41.164704],[..."
16,1372638481620000403,B,NaN,28.0,20000403,1372638481,A,False,"[[-8.584263,41.163156],[-8.584695,41.163003],[..."
17,1372639135620000570,A,33180.0,NaN,20000570,1372639135,A,False,"[[-8.666757,41.174055],[-8.666784,41.174064],[..."
18,1372637482620000005,C,NaN,NaN,20000005,1372637482,A,False,"[[-8.599239,41.149188],[-8.598681,41.149296],[..."
19,1372639181620000089,C,NaN,NaN,20000089,1372639181,A,False,"[[-8.643807,41.168979],[-8.642529,41.170113],[..."
20,1372638161620000423,C,NaN,NaN,20000423,1372638161,A,False,"[[-8.609706,41.151303],[-8.609562,41.151474],[..."
21,1372637254620000657,A,39233.0,NaN,20000657,1372637254,A,False,"[[-8.660646,41.168574],[-8.661087,41.167926],[..."
22,1372638502620000320,C,NaN,NaN,20000320,1372638502,A,False,"[[-8.612955,41.140377],[-8.612991,41.140359],[..."
23,1372639960620000309,B,NaN,38.0,20000309,1372639960,A,False,"[[-8.60418,41.160969],[-8.603874,41.1615],[-8...."
24,1372637658620000596,A,22864.0,NaN,20000596,1372637658,A,False,"[[-8.665686,41.170626],[-8.665677,41.170653],[..."
25,1372639092620000233,C,NaN,NaN,20000233,1372639092,A,False,"[[-8.632737,41.168295],[-8.6328,41.16825],[-8...."
26,1372639535620000161,A,25862.0,NaN,20000161,1372639535,A,False,"[[-8.648226,41.148333],[-8.648514,41.148297],[..."
27,1372640499620000596,C,NaN,NaN,20000596,1372640499,A,False,"[[-8.638227,41.159592],[-8.637543,41.15925],[-..."
28,1372639635620000178,B,NaN,52.0,20000178,1372639635,A,False,"[[-8.613243,41.154444],[-8.612811,41.153733],[..."
29,1372640555620000235,C,NaN,NaN,20000235,1372640555,A,False,"[[-8.611065,41.149431],[-8.611209,41.149368],[..."
...,...,...,...,...,...,...,...,...,...
1710640,1404151621620000543,C,NaN,NaN,20000543,1404151621,A,False,"[[-8.668845,41.152725],[-8.668179,41.15313],[-..."
1710641,1404152121620000383,C,NaN,NaN,20000383,1404152121,A,False,"[[-8.625726,41.166864],[-8.625717,41.166873],[..."
1710642,1404170192620000020,B,NaN,14.0,20000020,1404170192,A,False,"[[-8.610903,41.149449],[-8.610885,41.149503],[..."
1710643,1386603894620000970,C,NaN,NaN,20000970,1386603894,A,False,[]
1710644,1401596832620000609,B,NaN,38.0,20000609,1401596832,A,False,"[[-8.604171,41.161077],[-8.604036,41.161473],[..."
1710645,1404151410620000185,B,NaN,NaN,20000185,1404151410,A,False,"[[-8.628777,41.169807],[-8.628615,41.169807],[..."
1710646,1404172198620000260,B,NaN,26.0,20000260,1404172198,A,False,"[[-8.580267,41.159232],[-8.581743,41.159142],[..."
1710647,1404155241620000340,B,NaN,13.0,20000340,1404155241,A,False,"[[-8.628111,41.157423],[-8.628156,41.157378],[..."
1710648,1404171548620000364,C,NaN,NaN,20000364,1404171548,A,False,"[[-8.614323,41.123385],[-8.614152,41.123385],[..."
1710649,1404151498620000393,B,NaN,15.0,20000393,1404151498,A,False,"[[-8.58564,41.148585],[-8.585658,41.148567],[-..."
1710650,1404168899620000002,A,33357.0,NaN,20000002,1404168899,A,False,"[[-8.63568,41.171886],[-8.634924,41.171859],[-..."
1710651,1404153627620000187,A,2002.0,NaN,20000187,1404153627,A,False,"[[-8.574714,41.142681],[-8.574714,41.142681],[..."
1710652,1401475142620000312,C,NaN,NaN,20000312,1401475142,A,False,"[[-8.66754,41.238549],[-8.669502,41.239287],[-..."
1710653,1403935197620000205,A,16392.0,NaN,20000205,1403935197,A,False,"[[-8.66349,41.177466],[-8.663436,41.177502],[-..."
1710654,1404166892620000500,B,NaN,15.0,20000500,1404166892,A,False,"[[-8.585712,41.148828],[-8.586009,41.148972],[..."
1710655,1404143157620000389,C,NaN,NaN,20000389,1404143157,A,False,"[[-8.645364,41.148324],[-8.642538,41.148036],[..."
1710656,1404014448620000407,A,53537.0,NaN,20000407,1404014448,A,False,"[[-8.630973,41.152653],[-8.631423,41.152662],[..."
1710657,1380123541620000980,C,NaN,NaN,20000980,1380123541,A,False,"[[-8.689959,41.240241]]"
1710658,1373986578620000931,A,2002.0,NaN,20000931,1373986578,A,False,[]
1710659,1403941536620000213,A,52688.0,NaN,20000213,1403941536,A,False,"[[-8.574732,41.157099],[-8.574849,41.156775],[..."
1710660,1384165182620000170,C,NaN,NaN,20000170,1384165182,A,False,"[[-8.643303,41.13648]]"
1710661,1404164723620000332,B,NaN,15.0,20000332,1404164723,A,False,"[[-8.585703,41.148567],[-8.585739,41.148855],[..."
1710662,1404155105620000121,B,NaN,9.0,20000121,1404155105,A,False,"[[-8.606385,41.144742],[-8.606466,41.144742],[..."
1710663,1388660427620000585,C,NaN,NaN,20000585,1388660427,A,False,"[[-8.60697,41.162283],[-8.60697,41.16231],[-8...."
1710664,1390403767620000911,C,NaN,NaN,20000911,1390403767,A,False,[]
1710665,1404171463620000698,C,NaN,NaN,20000698,1404171463,A,False,"[[-8.612469,41.14602],[-8.612487,41.145993],[-..."
1710666,1404171367620000670,C,NaN,NaN,20000670,1404171367,A,False,"[[-8.610138,41.140845],[-8.610174,41.140935],[..."
1710667,1388745716620000264,C,NaN,NaN,20000264,1388745716,A,False,[]
1710668,1404141826620000248,B,NaN,12.0,20000248,1404141826,A,False,"[[-8.630712,41.154885],[-8.63073,41.154813],[-..."
1710669,1404157147620000079,B,NaN,34.0,20000079,1404157147,A,False,"[[-8.615538,41.140629],[-8.615421,41.140746],[..."

In [37]:
import ast

def convert_string(string):
    array = np.array(ast.literal_eval(string))
    return np.flip(array)

In [38]:
%%time
routes['polyline array'] = routes['POLYLINE'].map(convert_string)

Wall time: 12min 21s

In [45]:
import pickle
pickle.dump( routes, open( "save.p", "wb" ) )